sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=ripe_rainbow setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: platforme
  password:
    secure: EOazkbYL8OIzVJfbmEhGHls7rtlK0ViVGD0d6l+uuoqDrzzeAgc4XJkn7XS2dAmFdrY9ADA4BKmM8HttVF1ZFspD7Wl+fNu+MFyIfcI4NvJ1BhYbeiA6QtEq5S6kIH8CjykRdtPgZpTX0FLIE1WjZA41eNck59nBdpFlG2PVbEIuby0LgzI4XILHVVYsjxP7Ezg0fx8KCT7UP/yVwVJAMU46Kg5oocVpw1TTA6X87Wf0ix84yP81/MCFoVz1WvHY3CYHfwLMXnp0yCf/y5M6qFimduLPls/qjsMAIXMR+HCzHidLbeWYiYr/tG6sqGAGMa0IPnlqhhT0DYjqa2SZgv4oqnQqzJi63YkRSEjLn+YMiw37P7igeRjha0ytlEnn4+NuO5bzG2BWFpkq51gWnM1I4ygz9QYjBJ6pRY5hltGWDFaPVUCfonsWaAfj//l27/sQxXEQYKku+nDN03W6SG+8AOnb6lakyqugvPPCeq66FSbMxctiGh1U86jjzSoZmfcD0tVm9/8vrB4p30byIG9MTKg8xeWm6ToZHHi6uj5yRcEEZybmyR6QF39O7TK/p5vwdeOvuCsbYjCjyoQ/npy5N9cRfa4Grv6/THf/6q6ofQDzvMoZnNacMCgXjjHbmyyc2073WLBsfl2D8y28aJIvr9ZMPlNl+CU952LqRgQ=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
